### ISSUE TITLE
Create Sponsorship Package

### ISSUE THREAD

**Issue by stephenwang5** [stephenwang5/capstone#1]
[The slides](https://docs.google.com/presentation/d/1LIbcMmEYpmongZWDT79klS5ixEUWcOTKNwi9bVvmnuc/edit#slide=id.p) are saved on G drive

**Comment by niobiumneo** [comment]
Bro

**Comment by niobiumneo** [comment]
Ello mister i thought we are just using the same slides

**Comment by niobiumneo** [comment]
Here is the slide deck that we are using based on our discussion

https://docs.google.com/presentation/d/1qQfzwmC9KEeS1vSufmdVncGXcYMKX-Mm-XecoQXQ9bY/edit#slide=id.p
