### ISSUE TITLE
Contact Skydio Meeting #1

### ISSUE THREAD

**Issue by stephenwang5** [stephenwang5/capstone#3]

**Comment by niobiumneo** [comment]
Skydio contact acquired. 

Proceed to reach out to Daniel's contact

**Comment by niobiumneo** [comment]
Notes:
- Project too specific. Narrow down the problem
- UAV + Tooling is too broad
- Look into smaller subprojects for scope (eg - Gimbal on a drone)

Contact from some other contact within Skydio will coming soon

**Comment by niobiumneo** [comment]
OutcomeL
|
We want to make a drone that would fulfill one specific task in a specific problem (for example bridge)
