### ISSUE TITLE
Market Research

### ISSUE THREAD

**Issue by niobiumneo** [stephenwang5/capstone#6]
Check for other competitors, see if they have any other projects that might be better/worse than our potential solution

look into costs and how the features are diff/same to our potential solution

**Comment by stephenwang5** [comment]
https://docs.google.com/document/d/1bhYAICg5AC9b050dr8GigvMdsxMITSznCRWgPle9dMc/edit?usp=drive_link

**Comment by niobiumneo** [comment]
@josh-cai2001 @BANANAMOB Use the file pls and ty

**Comment by stephenwang5** [comment]
Out of the research results, here are the companies that we may invite to collaborate once we have a prototype.

- Zipline
  - Drone + base whole system automation
- Drone Matrix
  - Base
