### ISSUE TITLE
Contact Skygauge

### ISSUE THREAD

**Issue by niobiumneo** [stephenwang5/capstone#7]
Skygague seems to be creating drone systems for inspection. Sent email out to them for help on system architecture and cost (RFQ)

**Comment by niobiumneo** [comment]
Digging deeper on linkedin for contacts

**Comment by stephenwang5** [comment]
Any news?

**Comment by niobiumneo** [comment]
Skygauge has been a roadblock all they did was give me the pricing and didnt really get back to me.

I will try to see if I can get an engineer's contact via linkedin

**Comment by stephenwang5** [comment]
No contact so far. Gordon can make an introduction when we have a prototype to show them. Closing this for now
